# See https://desi.lbl.gov/trac/wiki/FPS/PositionerFlags
POSITIONER_FLAGS_BITS = {'MATCHED' : 0,
                         'PINHOLE' : 1,
                         'POSITIONER' : 2,
                         'FIDUCIAL' : 3,
                         'FVCERROR' : 4,
                         'BADPOSFID' : 5,
                         'MOVED' : 6,
                         'GIF' : 7,
                         'FVCPROC' : 12,
                         'ASSIGNED' : 14,
                         'CONVERGED' : 15,
                         'NOTCTLENABLED' : 16,
                         'BROKENFIBER' : 17,
                         'COMERROR' : 18,
                         'OVERLAP' : 19,
                         'FROZEN' : 20,
                         'UNREACHABLE' : 21,
                         'BOUNDARYVIOLATION' : 22,
                         'MULTIPLEREQUESTS' : 23,
                         'NONFUNCTIONAL' : 24,
                         'REJECTED' : 25,
                         'EXPERTLIMIT' : 26,
                         'BADNEIGHBOR' : 27,
                         'MISSINGSPOT' : 28,
                         'BADPERFORMANCE' : 29
                    }

POSITIONER_FLAGS_MASKS = {}
for k,v in POSITIONER_FLAGS_BITS.items():
    POSITIONER_FLAGS_MASKS[k] = 1<<v

POSITIONER_FLAGS_VERBOS = {'MATCHED' : 'Matched',
                           'PINHOLE' : 'Fiducial pinhole',
                           'POSITIONER' : 'Positioner',
                           'FIDUCIAL' : 'Fiducial',
                           'FVCERROR' : 'FVC error',
                           'BADPOSFID' : 'FVC bad posfid',
                           'MOVED' : 'Moved',
                           'GIF' : 'GIF',
                           'FVCPROC' : 'FVCPROC',
                           'ASSIGNED' : 'Target assiged',
                           'CONVERGED' : 'Converged on target',
                           'NOTCTLENABLED' : 'Control disabled',
                           'BROKENFIBER' : 'Fiber not intact',
                           'COMERROR' : 'CAN communication error',
                           'OVERLAP' : 'Overlapping targets',
                           'FROZEN' : 'Frozen by anticollision',
                           'UNREACHABLE' : 'Unreachable target',
                           'BOUNDARYVIOLATION' : 'Exceeds boundaries',
                           'MULTIPLEREQUESTS' : 'Multiple requests',
                           'NONFUNCTIONAL' : 'Device nonfunctional',
                           'REJECTED' : 'Movetable rejected',
                           'EXPERTLIMIT' : 'Exceeds expert limit',
                           'BADNEIGHBOR' : 'Bad neighbor',
                           'MISSINGSPOT' : 'Unmatched',
                           'BADPERFORMANCE' : 'Exceeded max error'
                    }